<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barang_model extends CI_Model
{

    public $table = 'barang';
    public $id = 'id_barang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    public function con($kode_po = "")
    {

        
        
                // $sql = $this->db->query("SELECT * FROM detail_po as a,barang as b where a.kode_barang=b.kode_barang and a.kode_po='$rs->kode_po' ");
                // $no = 1;
                // foreach ($sql->result() as $row) 
                
        $barang = $this->db->query("SELECT * FROM detail_po ");
        return $barang;
        
    }

     public function can($kode_po="")
    {

                
        $barang = $this->db->query("SELECT
 po.kode_po, po.tgl_po, po.total_harga ,
 barang.nama_barang , barang.harga,
 detail_po.qty
FROM po
  INNER JOIN detail_po
    ON po.kode_po = detail_po.kode_po
    
    INNER JOIN barang
    on detail_po.kode_barang=barang.kode_barang    
    
     where detail_po.kode_po" .$kode_po);
        return $barang;
        
    }
    public function barang2($where = ""){
        $barang = $this->db->query("select * from barang ".$where);
        return $barang;
    }
    function get_all2()
    {
    $this->db->select('*');
    $this->db->from('barang');
    $this->db->join('jenis_barang', 'jenis_barang.id_jenis = barang.id_jenis');

          $query = $this->db->get();
           return $query->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_barang', $q);
	$this->db->or_like('kode_barang', $q);
	$this->db->or_like('nama_barang', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('stok', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_barang', $q);
	$this->db->or_like('kode_barang', $q);
	$this->db->or_like('nama_barang', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('stok', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Barang_model.php */
/* Location: ./application/models/Barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-03 15:15:51 */
/* http://harviacode.com */